### Numpy

#### numpy 기본 1. 다차원 배열 만들기

In [ ]:
# numpy 임포트
import numpy as np

In [1]:
import numpy as np

In [ ]:
# 1차원 배열 생성하기
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [2]:
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [ ]:
# 2차원 배열 생성하기
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [4]:
넘파이_배열2 = np.array([[1,2,3,4], [11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [ ]:
# 3차원 배열 생성하기
넘파이_배열3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                [[21,22,23,24],[31,32,33,34]] ])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [5]:
넘파이_배열3  = np.array([ [[1,2,3,4],[11,12,13,14]],
                     [[21,22,23,24],[31,32,33,34]]])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [ ]:
# 배열의 모양 보기
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [7]:
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [ ]:
z1 = np.zeros([4])    # 0 으로 채운 배열 만들기
o2 = np.ones([3,4])   # 1 로 채운 배열 만들기
r2 = np.random.randn(2,3)   # 랜덤한 숫자 배열 만들기

In [10]:
z1 = np.zeros([4])
o2 = np.ones([3,4])
r2 = np.random.randn(2,3)

In [ ]:
z1, o2, r2

(array([0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[-0.5463959 , -1.29965629, -0.43717161],
        [-1.83098543,  1.37599679, -0.08877425]]))

In [ ]:
# 배열의 모양 보기
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [12]:
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [ ]:
# 무척 큰 4차원 배열 생성해보기
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 2.985, -1.633, -1.02 , -0.099, -1.98 ],
         [-0.273, -0.531, -0.393,  0.128,  0.018],
         [-0.121,  0.391, -0.491,  0.694,  0.853],
         [ 0.091,  0.453, -0.083, -0.051,  0.24 ]],

        [[-1.318, -0.503,  0.448, -1.078, -0.515],
         [ 0.046,  1.444,  0.188, -0.899, -0.745],
         [-1.375, -0.447,  0.353,  0.007, -0.307],
         [ 0.302, -0.848, -0.609,  0.1  , -0.124]]],


       [[[-0.625, -0.338,  0.968, -0.309, -1.093],
         [-0.035, -1.171, -1.622,  0.714, -0.756],
         [-0.38 ,  2.061, -1.237, -0.558, -1.787],
         [ 2.575,  1.109, -0.498, -1.05 ,  0.168]],

        [[ 0.487, -0.441,  0.247, -1.274, -0.379],
         [ 0.212,  0.156, -0.138,  1.336, -0.016],
         [-1.747,  1.056,  0.209,  0.779,  0.839],
         [ 0.329,  0.599, -0.032, -0.689, -1.579]]]])

In [14]:
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 1.208, -1.757, -0.091, -0.044, -0.492],
         [ 0.601,  0.518,  0.713, -1.446, -0.818],
         [ 0.232,  0.417, -0.996, -0.734,  1.095],
         [ 0.273, -0.311, -1.049, -1.048,  0.938]],

        [[-1.484, -0.238, -1.122, -0.341, -1.159],
         [-0.165, -0.772,  0.841, -1.117, -0.376],
         [-0.09 , -0.065, -0.908,  0.319,  0.544],
         [ 1.305, -0.039,  1.471, -1.089, -1.043]]],


       [[[ 0.823, -1.229, -2.239,  0.714,  1.436],
         [-0.179, -0.413, -1.603, -0.16 ,  1.524],
         [-1.504,  2.125, -1.677,  0.476, -0.254],
         [-0.039,  0.451, -0.01 ,  0.243, -1.073]],

        [[-0.767,  1.259,  0.29 , -1.507, -0.194],
         [-0.114,  1.272, -1.059,  0.333,  0.375],
         [-0.177, -1.221, -1.109, -0.685, -0.077],
         [ 1.064, -0.075, -0.727,  1.889,  1.661]]]])

#### numpy 기본 2. Indexing과 Slicing

In [ ]:
# r4 배열에서, [두번째][첫번째] 접근해서 가져오기
r4[1][0]

array([[-0.625, -0.338,  0.968, -0.309, -1.093],
       [-0.035, -1.171, -1.622,  0.714, -0.756],
       [-0.38 ,  2.061, -1.237, -0.558, -1.787],
       [ 2.575,  1.109, -0.498, -1.05 ,  0.168]])

In [15]:
r4[1][0]

array([[ 0.823, -1.229, -2.239,  0.714,  1.436],
       [-0.179, -0.413, -1.603, -0.16 ,  1.524],
       [-1.504,  2.125, -1.677,  0.476, -0.254],
       [-0.039,  0.451, -0.01 ,  0.243, -1.073]])

In [ ]:
r4[1][0][2]

array([-0.38 ,  2.061, -1.237, -0.558, -1.787])

In [18]:
r4[1][0][2]

array([-1.504,  2.125, -1.677,  0.476, -0.254])

In [ ]:
r4[1][0][2][4]

-1.787

In [19]:
r4[1][0][2][4]

-0.254

In [ ]:
r4[1,0,2,4]   # 대괄호 대신 쉼표 , 도 차원 접근이 가능

-1.787

In [20]:
r4[1,0,2,4]

-0.254

In [ ]:
r4[1][0][2][0:4:2]

array([-0.38 , -1.237])

In [22]:
r4[1][0][2][0:4:2]

array([-1.504, -1.677])

In [ ]:
r4[1][0][1:4:2]

array([[-0.035, -1.171, -1.622,  0.714, -0.756],
       [ 2.575,  1.109, -0.498, -1.05 ,  0.168]])

In [23]:
r4[1][0][1:4:2]

array([[-0.179, -0.413, -1.603, -0.16 ,  1.524],
       [-0.039,  0.451, -0.01 ,  0.243, -1.073]])

In [ ]:
# Indexing과 Slicing 같이 적용하기
r4[1][0][1:4:2][1][3:]

array([-1.05 ,  0.168])

In [24]:
r4[1][0][1:4:2][1][3:]

array([ 0.243, -1.073])

In [ ]:
r4[1,0][1:4:2][1,3:]   # 모두 다 짬뽕!!

array([-1.05 ,  0.168])

In [25]:
r4[1,0][1:4:2][1,3:]

array([ 0.243, -1.073])

#### numpy 기본 3. 배열 간 연산, Broadcasting, Aggregation

In [ ]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [26]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [ ]:
arr + arr    # 배열끼리 연산하기 (＋－*/ 모두 가능)

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [27]:
arr+arr

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [ ]:
arr + 20     # 덧셈 브로드캐스팅

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [28]:
arr + 20

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [ ]:
arr * 100    # 곱셈 브로드캐스팅

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [29]:
arr * 100

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [ ]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [31]:
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [ ]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [32]:
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [ ]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [33]:
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [ ]:
# Indexing + Slicing + Aggregation 응용
arr[1].min(), arr[1][2:].sum()

(10, 25)

In [34]:
arr[1].min(), arr[1][2:].sum()

(10, 25)

#### numpy 기본 4. 고급 Broadcasting

In [ ]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [37]:
arr1= np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [ ]:
arr1 + arr2          # (4x3)  +  (4x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [38]:
arr1+arr2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
arr1 + np.array([0,1,2])     # (4x3) + (1x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [40]:
arr1 + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
#  (4x1) + (1x3)
np.array([[0],[10],[20],[30]]) + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [42]:
np.array([[0], [10],[20],[30]]) + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])